apiVersion: v1
kind: Namespace
metadata:
  name: comments-zipkin-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-zipkin-pod # Base POD name
  namespace: comments-zipkin-system
spec:
  selector:
    matchLabels:
      app: zipkin # Selector for POD name search.
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      # zipkin container configuration
      - name: zipkin
        image: openzipkin
        ports:
        - name: zipkin
          containerPort: 9413
---
apiVersion: v1
kind: Service
metadata:
  name: comments-zipkin-service
  namespace: comments-zipkin-system
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
  - name: zipkin
    port: 9413
    targetPort: zipkin