apiVersion: v1
kind: Namespace
metadata:
  name: services-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-pod
  namespace: services-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats
          ports:
          - name: client
            containerPort: 4222
          - name: monitoring
            containerPort: 8222
          args: [
            '-p',
            '4222',
            '-m',
            '8222',
            '-hbi',
            '5s',
            '-hbt',
            '5s',
            '-hbf',
            '2',
            '-SD',
            '-cid',
            'social-network'
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: services-system
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: client
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: monitoring