apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kind-nats.yaml
patchesStrategicMerge:
- ./kind-nats-patch.yaml
images:
- name: nats
  newName: nats-streaming
  newTag: "0.17.0"