apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-pod
  namespace: services-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
      # comments-api container configuration
      - name: comments-api
        resources:
          limits:
            cpu: "500m" # Up to 1/2 full cores
          requests:
            cpu: "250m" # Use 1/4 full cores