apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/comments-pod/
patchesStrategicMerge:
- ./kind-comments-patch.yaml
images:
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
- name: comments-api-image
  newName: comments-api-amd64
  newTag: "1.0"
