apiVersion: v1
kind: Namespace
metadata:
  name: posts-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-pod # Base POD name
  namespace: posts-system
spec:
  selector:
    matchLabels:
      app: posts # Selector for POD name search.
  template:
    metadata:
      labels:
        app: posts
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      initContainers:
      # posts-api init container configuration
      - name: init-migrate
        image: posts-api-image
        command: ['./admin']
      containers:
      - name: posts-api
        image: posts-api-image
        ports:
        - name: posts-api
          containerPort: 3001
        - name: posts-api-debug
          containerPort: 4001
        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /debug/readiness
            port: 4001
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /debug/liveness
            port: 4001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
  namespace: posts-system
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
  - name: posts-api
    port: 3001
    targetPort: posts-api
  - name: posts-api-debug
    port: 4001
    targetPort: posts-api-debug