apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/email-pod/
patchesStrategicMerge:
- ./kind-email-patch.yaml
images:
- name: email-api-image
  newName: email-api-amd64
  newTag: "1.0"
