apiVersion: v1
kind: Namespace
metadata:
  name: comments-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-pod # Base POD name
  namespace: comments-system
spec:
  selector:
    matchLabels:
      app: comments # Selector for POD name search.
  template:
    metadata:
      labels:
        app: comments
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      initContainers:
      # comments-api init container configuration
      - name: init-migrate
        image: comments-api-image
        command: ['./admin']
      containers:
      - name: comments-api
        image: comments-api-image
        ports:
        - name: comments-api
          containerPort: 3002
        - name: comments-api-dg
          containerPort: 4002
        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /debug/readiness
            port: 4002
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /debug/liveness
            port: 4002
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: comments-service
  namespace: comments-system
spec:
  type: ClusterIP
  selector:
    app: comments
  ports:
  - name: comments-api
    port: 3002
    targetPort: comments-api
  - name: comments-api-dg
    port: 4002
    targetPort: comments-api-dg