apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/users-pod/
patchesStrategicMerge:
- ./kind-users-patch.yaml
images:
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
- name: users-api-image
  newName: users-api-amd64
  newTag: "1.0"
