apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/posts-pod/
patchesStrategicMerge:
- ./kind-posts-patch.yaml
images:
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
- name: posts-api-image
  newName: posts-api-amd64
  newTag: "1.0"
